from day01 import day01
from helpers import helpers

input_lines = helpers.parse_input("day01/input.txt")
day01.do_part_1(input_lines)
day01.do_part_2(input_lines)
# input_lines = helpers.parse_input("day02/input.txt")
# day02.do_part_1(input_lines)
# day02.do_part_2(input_lines)
# input_lines = helpers.parse_input("day03/input.txt")
# day03.do_part_1(input_lines)
# input_lines = helpers.parse_input("day03/input.txt")
# day03.do_part_1(input_lines)
# input_lines = helpers.parse_input("day04/input.txt")
# day04.do_part_1(input_lines)
# day04.do_part_2(input_lines)
# input_lines = helpers.parse_input("day05/input.txt")
# day05.do_part_1(input_lines)
# day05.do_part_2(input_lines)
# input_lines = helpers.parse_input("day06/input.txt")
# day06.do_part_1(input_lines)
# day06.do_part_2(input_lines)
# input_lines = helpers.parse_input("day07/input.txt")
# day07.do_part_1(input_lines)
# day07.do_part_2(input_lines)
# input_lines = helpers.parse_input("day08/input.txt")
# day08.do_part_1(input_lines)
# day08.do_part_2(input_lines)
# input_lines = helpers.parse_input("day09/input.txt")
# day09.do_part_1(input_lines)
# day09.do_part_2(input_lines)
# input_lines = helpers.parse_input("day10/input.txt")
# day10.do_part_1(input_lines)
# day10.do_part_2(input_lines)
# input_lines = helpers.parse_input("day11/input.txt")
# day11.do_part_1(input_lines)
# day11.do_part_2(input_lines)
# input_lines = helpers.parse_input("day12/input.txt")
# day12.do_part_1(input_lines)
# day12.do_part_2(input_lines)
# input_lines = helpers.parse_input("day13/example1.txt")
# day13.do_part_1(input_lines)
# day13.do_part_2(input_lines)
# input_lines = helpers.parse_input("day14/example1.txt")
# day14.do_part_1(input_lines)
# day14.do_part_2(input_lines)